language: python

python:
  - "3.4"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update
  - sudo apt-get upgrade

install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -e ."

script: 
  - "py.test dendrogenous/test" 
