language: python

python:
  - "3.4"

install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install six"
  - "pip install git+git://github.com/fmaguire/ete.git"
  - "pip install -e ."

script: 
  - "python setup.py test"
